#!/usr/bin/env sh
function echoBright() {
    echo -e "\033[1;33m$1\033[0m"
}
echoBright "🟡 Running pre-commit checks..."

echoBright "🟡 Running spell check..."
if ! npm run spell:check:errors; then
    echoBright "⚠️ Spell check has failed, fix the issue(s) before committing"
    exit 1
fi
echoBright "✅ Spell check has passed!"

echoBright "🟡 Running static analysis..."
# if ! npm run format:check; then
#     echoBright "⚠️ Static analysis has failed, fix the issue(s) before committing"
#     exit 1
# fi
echoBright "✅ Static analysis has passed!"

echoBright "🟡 Running linting..."
# if ! npm run lint:check:errors; then
#     echoBright "⚠️ Linting has failed, fix the issue(s) before committing"
#     exit 1
# fi
echoBright "✅ Linting has passed!"

echoBright "🟡 Running tests..."
#if ! npm run test; then
#echoBright "⚠️ Tests have failed, fix the failing test(s) before committing"
#exit 1
#fi
echoBright "✅ React tests passed"

echoBright "✅ All pre-commit checks passed!"
