name: Duster Lint

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  duster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: "Duster Lint"
        uses: tighten/duster-action@v3
        with:
          args: lint
